DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS categories;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE categories (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  alias TEXT UNIQUE NOT NULL,
  title TEXT NOT NULL,
  parents TEXT,
  whitelist TEXT,
  blacklist TEXT
);

INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'afghani', 'Afghan', 'restaurants', NULL, 'TR,MX');
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'african', 'African', 'restaurants', NULL, 'TR');
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'andalusian', 'Andalusian', 'restaurants', 'ES,IT', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'arabian', 'Arabian', 'restaurants', NULL, 'DK');
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'argentine', 'Argentine', 'restaurants', NULL, 'FI');
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'armenian', 'Armenian', 'restaurants', 'ES,PL,TR,AR,CZ,BE,FR,IT,GB,US', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'asianfusion', 'Asian Fusion', 'restaurants', NULL, NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'asturian', 'Asturian', 'restaurants', 'ES', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'australian', 'Australian', 'restaurants', NULL, NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'austrian', 'Austrian', 'restaurants', NULL, 'DK,ES');
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'baguettes', 'Baguettes', 'restaurants', 'SE,TR,CZ,PT,MX,IT,DE,NO', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'bangladeshi', 'Bangladeshi', 'restaurants', NULL, 'ES,TR,MX,DK,PT');
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'basque', 'Basque', 'restaurants', NULL, 'TR,AU,SG,DK,CZ,PT');
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'bavarian', 'Bavarian', 'restaurants', 'CH,DE,AT', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'bbq', 'Barbeque', 'restaurants', NULL, 'BR,AU');
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'beergarden', 'Beer Garden', 'restaurants', 'CH,DE,CZ,AT', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'beerhall', 'Beer Hall', 'restaurants', 'CH,DE,AT', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'beisl', 'Beisl', 'restaurants', 'AT', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'belgian', 'Belgian', 'restaurants', NULL, NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'bistros', 'Bistros', 'restaurants', NULL, 'US');
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'blacksea', 'Black Sea', 'restaurants', 'TR', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'brasseries', 'Brasseries', 'restaurants', NULL, 'AR,MX');
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'brazilian', 'Brazilian', 'restaurants', NULL, NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'breakfast_brunch', 'Breakfast & Brunch', 'restaurants', NULL, NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'british', 'British', 'restaurants', NULL, 'FI');
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'buffets', 'Buffets', 'restaurants', NULL, NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'bulgarian', 'Bulgarian', 'restaurants', NULL, 'BR,TR,NZ,DK,CA,SG,NO,NL');
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'burgers', 'Burgers', 'restaurants', NULL, NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'burmese', 'Burmese', 'restaurants', NULL, 'ES,TR,DK,FI,PT,CZ');
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'cafes', 'Cafes', 'restaurants', NULL, 'ES,AR,FI,MX');
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'cafeteria', 'Cafeteria', 'restaurants', NULL, 'BR,CA,SE,FR,SG,NZ,IE');
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'cajun', 'Cajun/Creole', 'restaurants', NULL, 'ES,AU,PT,SG');
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'cambodian', 'Cambodian', 'restaurants', NULL, 'ES,TR,DK,FI,PT,CZ');
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'canteen', 'Canteen', 'restaurants', 'CH,PL,DK,CZ,AT,FI,BE,JP,IT,DE,NO,NL', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'caribbean', 'Caribbean', 'restaurants', NULL, 'TR,FI,PT');
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'catalan', 'Catalan', 'restaurants', 'ES,TR,AR,PT,CL,FR,MX,IT,US', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'cheesesteaks', 'Cheesesteaks', 'restaurants', 'CA,PL,AU,IE,NL,GB,US', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'chicken_wings', 'Chicken Wings', 'restaurants', NULL, 'CH,ES,DK,FI,PT,BE,CL,FR,JP,IT,NO,NL');
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'chickenshop', 'Chicken Shop', 'restaurants', NULL, 'CZ');
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'chilean', 'Chilean', 'restaurants', 'BR,CL,FR,FI', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'chinese', 'Chinese', 'restaurants', NULL, NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'comfortfood', 'Comfort Food', 'restaurants', 'CA,CL,JP,MX,AR,FI,US', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'corsican', 'Corsican', 'restaurants', 'BE,FR', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'creperies', 'Creperies', 'restaurants', NULL, NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'cuban', 'Cuban', 'restaurants', NULL, 'DK,TR,SG');
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'currysausage', 'Curry Sausage', 'restaurants', 'CH,DE,AT', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'cypriot', 'Cypriot', 'restaurants', 'CH,DE,AT', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'czech', 'Czech', 'restaurants', 'PL,SE,IE,NO,DK,CZ,FI,CA,BE,FR,AU,IT,DE,GB,US', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'czechslovakian', 'Czech/Slovakian', 'restaurants', 'PT,AR,MX', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'danish', 'Danish', 'restaurants', 'SE,DK,FR,NO', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'delis', 'Delis', 'restaurants', NULL, 'BE,CL,SE,FR,IT,PT,NL');
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'diners', 'Diners', 'restaurants', NULL, 'SE,FI,AU,CZ');
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'dinnertheater', 'Dinner Theater', 'restaurants', NULL, 'BE,JP,FR,IT,NL');
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'dumplings', 'Dumplings', 'restaurants', 'CH,PL,IE,GB,AT,CA,BE,JP,AU,SG,DE,NZ,NL', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'eastern_european', 'Eastern European', 'restaurants', 'FR,AU,NO,DK,CZ', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'eltern_cafes', 'Parent Cafes', 'restaurants', 'CH,DE,AT', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'eritrean', 'Eritrean', 'restaurants', 'CH,IT,DE,AT,US', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'ethiopian', 'Ethiopian', 'restaurants', NULL, 'TR,MX,CZ,SG');
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'filipino', 'Filipino', 'restaurants', NULL, 'TR,DK,FI,CZ');
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'fischbroetchen', 'Fischbroetchen', 'restaurants', 'DE', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'fishnchips', 'Fish & Chips', 'restaurants', NULL, 'BR,PT');
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'flatbread', 'Flatbread', 'restaurants', 'CH,PL,DK,DE,AT', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'fondue', 'Fondue', 'restaurants', NULL, 'DK,CZ,ES');
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'food_court', 'Food Court', 'restaurants', NULL, 'TR,TW,FR,FI');
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'foodstands', 'Food Stands', 'restaurants', NULL, NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'freiduria', 'Freiduria', 'restaurants', 'MX,CL,AR,ES', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'french', 'French', 'restaurants', NULL, NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'galician', 'Galician', 'restaurants', 'ES,PT', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'gamemeat', 'Game Meat', 'restaurants', NULL, 'PH,BR,TR,HK,AR,FI,PT,CA,CL,JP,MX,MY,TW');
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'gastropubs', 'Gastropubs', 'restaurants', NULL, NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'georgian', 'Georgian', 'restaurants', 'CH,PL,CZ,AT,FI,DE,GB,US', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'german', 'German', 'restaurants', NULL, NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'giblets', 'Giblets', 'restaurants', 'TR', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'gluten_free', 'Gluten-Free', 'restaurants', NULL, NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'greek', 'Greek', 'restaurants', NULL, NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'guamanian', 'Guamanian', 'restaurants', NULL, 'PL,CL,TR,JP,FR,MX,AR');
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'halal', 'Halal', 'restaurants', NULL, 'TR,PT');
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'hawaiian', 'Hawaiian', 'restaurants', NULL, 'TR,AU,DK,CZ,PT');
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'heuriger', 'Heuriger', 'restaurants', 'AT', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'himalayan', 'Himalayan/Nepalese', 'restaurants', NULL, NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'hkcafe', 'Hong Kong Style Cafe', 'restaurants', 'US,HK,TW,CA', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'honduran', 'Honduran', 'restaurants', NULL, 'TR,JP');
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'hotdog', 'Hot Dogs', 'restaurants', NULL, NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'hotdogs', 'Fast Food', 'restaurants', NULL, NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'hotpot', 'Hot Pot', 'restaurants', 'PH,BR,SE,HK,CA,JP,FR,MY,SG,TW,US', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'hungarian', 'Hungarian', 'restaurants', NULL, NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'iberian', 'Iberian', 'restaurants', 'CA,PT,US', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'indonesian', 'Indonesian', 'restaurants', NULL, 'ES,MX');
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'indpak', 'Indian', 'restaurants', NULL, NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'international', 'International', 'restaurants', NULL, 'PH,TR,MY,IT,FI,US');
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'irish', 'Irish', 'restaurants', NULL, NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'island_pub', 'Island Pub', 'restaurants', 'SE', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'israeli', 'Israeli', 'restaurants', 'CH,DE,CZ,AT', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'italian', 'Italian', 'restaurants', NULL, NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'japanese', 'Japanese', 'restaurants', NULL, NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'jewish', 'Jewish', 'restaurants', 'PL,DE,IT', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'kebab', 'Kebab', 'restaurants', NULL, NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'kopitiam', 'Kopitiam', 'restaurants', 'MY,SG', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'korean', 'Korean', 'restaurants', NULL, NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'kosher', 'Kosher', 'restaurants', NULL, 'TR,PT');
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'kurdish', 'Kurdish', 'restaurants', 'SE,NO', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'laos', 'Laos', 'restaurants', 'AU', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'laotian', 'Laotian', 'restaurants', NULL, 'CZ');
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'latin', 'Latin American', 'restaurants', NULL, NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'lyonnais', 'Lyonnais', 'restaurants', 'BE,FR', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'malaysian', 'Malaysian', 'restaurants', NULL, 'ES,TR,CZ,PT');
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'meatballs', 'Meatballs', 'restaurants', 'TR,BE,FR,NL', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'mediterranean', 'Mediterranean', 'restaurants', NULL, NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'mexican', 'Mexican', 'restaurants', NULL, NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'mideastern', 'Middle Eastern', 'restaurants', NULL, 'BR');
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'milkbars', 'Milk Bars', 'restaurants', 'PL,AU', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'modern_australian', 'Modern Australian', 'restaurants', 'AU', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'modern_european', 'Modern European', 'restaurants', NULL, NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'mongolian', 'Mongolian', 'restaurants', NULL, 'ES,TR,FI,PT');
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'moroccan', 'Moroccan', 'restaurants', NULL, 'TR');
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'newamerican', 'American (New)', 'restaurants', 'SE,IE,GB,DK,NO,US', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'newcanadian', 'Canadian (New)', 'restaurants', 'CA', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'newmexican', 'New Mexican Cuisine', 'restaurants', 'US', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'newzealand', 'New Zealand', 'restaurants', 'NZ', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'nicaraguan', 'Nicaraguan', 'restaurants', NULL, 'CL,AR');
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'nightfood', 'Night Food', 'restaurants', 'PL,TR,SE,DK,NO', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'nikkei', 'Nikkei', 'restaurants', 'BR,ES,CL,MX,AR', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'noodles', 'Noodles', 'restaurants', NULL, 'CH,FR,DE,AT');
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'norcinerie', 'Norcinerie', 'restaurants', 'IT', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'norwegian', 'Traditional Norwegian', 'restaurants', 'FR,NO', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'opensandwiches', 'Open Sandwiches', 'restaurants', 'TR,DK,SE,NO', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'oriental', 'Oriental', 'restaurants', 'CH,PL,AT,FR,DE,PT', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'pakistani', 'Pakistani', 'restaurants', NULL, NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'panasian', 'Pan Asian', 'restaurants', NULL, 'IT');
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'parma', 'Parma', 'restaurants', 'AU', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'persian', 'Persian/Iranian', 'restaurants', NULL, NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'peruvian', 'Peruvian', 'restaurants', NULL, 'TR,PT,SG');
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'pfcomercial', 'PF/Comercial', 'restaurants', 'BR', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'pita', 'Pita', 'restaurants', 'TR', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'pizza', 'Pizza', 'restaurants', NULL, NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'polish', 'Polish', 'restaurants', NULL, 'FI,SG');
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'polynesian', 'Polynesian', 'restaurants', 'US', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'popuprestaurants', 'Pop-Up Restaurants', 'restaurants', 'PH,NO,GB,BE,FR,MY,AU,NZ,US,SE,HK,DK,CA,TW,SG,DE,IE,NL', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'portuguese', 'Portuguese', 'restaurants', NULL, 'FI');
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'potatoes', 'Potatoes', 'restaurants', 'CH,DE,AU,AT', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'poutineries', 'Poutineries', 'restaurants', 'CA,US', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'pubfood', 'Pub Food', 'restaurants', 'AU', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'raw_food', 'Live/Raw Food', 'restaurants', NULL, NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'riceshop', 'Rice', 'restaurants', 'TR,JP', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'romanian', 'Romanian', 'restaurants', 'CH,ES,PL,CZ,AT,BE,FR,DE', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'rotisserie_chicken', 'Rotisserie Chicken', 'restaurants', 'BR,ES,PL,AR,PT,BE,CL,FR,AU,IT,MX,NZ,NL', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'russian', 'Russian', 'restaurants', NULL, NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'salad', 'Salad', 'restaurants', NULL, NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'sandwiches', 'Sandwiches', 'restaurants', NULL, NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'scandinavian', 'Scandinavian', 'restaurants', NULL, 'PT');
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'schnitzel', 'Schnitzel', 'restaurants', 'CH,PL,DE,AT', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'scottish', 'Scottish', 'restaurants', 'CH,CA,GB,DE,IE,AT,US', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'seafood', 'Seafood', 'restaurants', NULL, NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'serbocroatian', 'Serbo Croatian', 'restaurants', 'CH,PL,SE,AR,CZ,AT,BE,CL,FR,IT,DE', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'signature_cuisine', 'Signature Cuisine', 'restaurants', 'ES,SE,DK,AR,PT,CL,MX,NO', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'singaporean', 'Singaporean', 'restaurants', NULL, 'ES,TR,DK,FI,PT,CZ');
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'slovakian', 'Slovakian', 'restaurants', 'PL,IE,CZ,CA,BE,FR,AU,IT,GB,US', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'somali', 'Somali', 'restaurants', 'CH,PL,IT,DE,AT,US', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'soulfood', 'Soul Food', 'restaurants', 'ES,PL,SE,IE,NO,CA,US,GB,NL', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'soup', 'Soup', 'restaurants', NULL, NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'southern', 'Southern', 'restaurants', 'PL,SE,IE,TR,GB,CA,US,NZ,NL', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'spanish', 'Spanish', 'restaurants', NULL, NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'srilankan', 'Sri Lankan', 'restaurants', NULL, 'CZ');
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'steak', 'Steakhouses', 'restaurants', NULL, NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'sud_ouest', 'French Southwest', 'restaurants', 'BE,FR', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'supperclubs', 'Supper Clubs', 'restaurants', 'CA,ES,GB,US', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'sushi', 'Sushi Bars', 'restaurants', NULL, NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'swabian', 'Swabian', 'restaurants', 'CH,DE,AT', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'swedish', 'Swedish', 'restaurants', 'SE', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'swissfood', 'Swiss Food', 'restaurants', 'CH,ES,CL,MX,DE,AR,CZ', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'syrian', 'Syrian', 'restaurants', NULL, NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'tabernas', 'Tabernas', 'restaurants', 'ES,TR,PT', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'taiwanese', 'Taiwanese', 'restaurants', NULL, 'ES,TR,FI,PT,CZ');
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'tapas', 'Tapas Bars', 'restaurants', NULL, 'FI,AU,SG');
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'tapasmallplates', 'Tapas/Small Plates', 'restaurants', NULL, NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'tavolacalda', 'Tavola Calda', 'restaurants', 'IT', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'tex-mex', 'Tex-Mex', 'restaurants', NULL, 'DK,AU,ES,PT');
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'thai', 'Thai', 'restaurants', NULL, NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'tradamerican', 'American (Traditional)', 'restaurants', NULL, NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'traditional_swedish', 'Traditional Swedish', 'restaurants', 'SE,FI', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'trattorie', 'Trattorie', 'restaurants', 'CH,PL,CL,FR,IT,AR', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'turkish', 'Turkish', 'restaurants', NULL, NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'ukrainian', 'Ukrainian', 'restaurants', NULL, 'DK,TR,ES');
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'uzbek', 'Uzbek', 'restaurants', 'CZ,US', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'vegan', 'Vegan', 'restaurants', NULL, NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'vegetarian', 'Vegetarian', 'restaurants', NULL, NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'venison', 'Venison', 'restaurants', 'PL,IE,NO,NZ,DK,CZ,CA,AU,IT,SG,GB', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'vietnamese', 'Vietnamese', 'restaurants', NULL, NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'waffles', 'Waffles', 'restaurants', NULL, NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'wok', 'Wok', 'restaurants', NULL, 'BR,PL,TR,IE,NZ,HK,AR,CA,TW,JP,AU,IT,SG,GB,US');
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'wraps', 'Wraps', 'restaurants', 'SE,TR,NO,DK,CZ,PT,US', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'yugoslav', 'Yugoslav', 'restaurants', 'BE,SE,FR,AU,IT,PT', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'abruzzese', 'Abruzzese', 'italian', 'IT', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'alentejo', 'Alentejo', 'portuguese', 'PT', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'algarve', 'Algarve', 'portuguese', 'PT', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'alsatian', 'Alsatian', 'french', 'FR,DE', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'altoatesine', 'Altoatesine', 'italian', 'IT', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'apulian', 'Apulian', 'italian', 'FR,IT', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'arabpizza', 'Arab Pizza', 'arabian', 'BR', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'arroceria_paella', 'Arroceria / Paella', 'spanish', 'ES', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'auvergnat', 'Auvergnat', 'french', 'FR', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'azores', 'Azores', 'portuguese', 'PT', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'baden', 'Baden', 'german', 'DE', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'beira', 'Beira', 'portuguese', 'PT', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'berrichon', 'Berrichon', 'french', 'FR', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'blowfish', 'Blowfish', 'japanese', 'JP', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'bourguignon', 'Bourguignon', 'french', 'FR', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'brazilianempanadas', 'Brazilian Empanadas', 'brazilian', 'BR', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'calabrian', 'Calabrian', 'italian', 'FR,IT,US', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'cantonese', 'Cantonese', 'chinese', 'AR,BE,FR,JP,IT,AU,MY,NZ,US,SE,HK,CA,TW,SG,GB,NL', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'centralbrazilian', 'Central Brazilian', 'brazilian', 'BR', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'cheekufta', 'Chee Kufta', 'turkish', 'TR,DE', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'colombian', 'Colombian', 'latin', 'ES,AR,FI,CA,BE,CL,FR,MX,US', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'congee', 'Congee', 'chinese', 'HK,MY,TW,SG', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'conveyorsushi', 'Conveyor Belt Sushi', 'japanese', 'CH,PL,SE,HK,AT,BE,JP,IT,SG,US,DE,TW,NL', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'cucinacampana', 'Cucina campana', 'italian', 'IT', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'dimsum', 'Dim Sum', 'chinese', NULL, 'BR,TR,PT');
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'dominican', 'Dominican', 'caribbean', 'US', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'donburi', 'Donburi', 'japanese', 'HK,JP,TW', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'easterngerman', 'Eastern German', 'german', 'DE', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'easternmexican', 'Eastern Mexican', 'mexican', 'MX', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'egyptian', 'Egyptian', 'mideastern', 'CA,BE,FR,IT,US', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'emilian', 'Emilian', 'italian', 'IT', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'fado_houses', 'Fado Houses', 'portuguese', 'PT', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'falafel', 'Falafel', 'mediterranean', NULL, 'PT,AR,MX');
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'flemish', 'Flemish', 'belgian', 'FR', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'franconian', 'Franconian', 'german', 'DE', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'friulan', 'Friulan', 'italian', 'IT', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'fuzhou', 'Fuzhou', 'chinese', 'HK,MY,TW,SG', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'gozleme', 'Gozleme', 'turkish', 'TR', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'hainan', 'Hainan', 'chinese', 'PH,MY,SG,HK,US', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'haitian', 'Haitian', 'caribbean', 'CA,US', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'hakka', 'Hakka', 'chinese', 'PH,CA,MY,SG,HK,TW', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'handrolls', 'Hand Rolls', 'japanese', 'BR,TW', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'henghwa', 'Henghwa', 'chinese', 'HK,MY,TW,SG', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'hessian', 'Hessian', 'german', 'DE', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'hokkien', 'Hokkien', 'chinese', 'HK,MY,TW,SG', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'homemadefood', 'Homemade Food', 'turkish', 'TR', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'horumon', 'Horumon', 'japanese', 'JP,TW', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'hunan', 'Hunan', 'chinese', 'MY,FR,SG,HK,TW', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'izakaya', 'Izakaya', 'japanese', 'BR,HK,TW,JP,AU,MX,SG,NZ,US', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'jaliscan', 'Jaliscan', 'mexican', 'MX', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'japacurry', 'Japanese Curry', 'japanese', 'JP,SG,HK,TW,US', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'kaiseki', 'Kaiseki', 'japanese', 'JP,TW', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'kushikatsu', 'Kushikatsu', 'japanese', 'JP', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'lahmacun', 'Lahmacun', 'turkish', 'TR', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'lebanese', 'Lebanese', 'mideastern', NULL, 'JP,HK,AR');
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'ligurian', 'Ligurian', 'italian', 'FR,IT', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'lumbard', 'Lumbard', 'italian', 'IT', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'madeira', 'Madeira', 'portuguese', 'PT', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'mamak', 'Mamak', 'malaysian', 'MY,AU', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'mauritius', 'Mauritius', 'french', NULL, 'CH,BR,PL,TR,NZ,DK,AR,AT,CL,JP,AU,MX,DE,NO');
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'minho', 'Minho', 'portuguese', 'PT', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'napoletana', 'Napoletana', 'italian', 'FR,CZ,IT', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'nicois', 'Nicoise', 'french', 'FR', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'northeasternbrazilian', 'Northeastern Brazilian', 'brazilian', 'BR', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'northernbrazilian', 'Northern Brazilian', 'brazilian', 'BR', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'northerngerman', 'Northern German', 'german', 'DE', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'northernmexican', 'Northern Mexican', 'mexican', 'MX', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'nyonya', 'Nyonya', 'malaysian', 'MY,AU', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'oaxacan', 'Oaxacan', 'mexican', 'MX', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'oden', 'Oden', 'japanese', 'JP,TW', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'okinawan', 'Okinawan', 'japanese', 'JP', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'okonomiyaki', 'Okonomiyaki', 'japanese', 'JP,TW', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'onigiri', 'Onigiri', 'japanese', 'JP,TW', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'ottomancuisine', 'Ottoman Cuisine', 'turkish', 'TR', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'palatine', 'Palatine', 'german', 'DE', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'pancakes', 'Pancakes', 'breakfast_brunch', NULL, NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'pekinese', 'Pekinese', 'chinese', 'JP,MY,FR,IT,HK,SG,TW', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'piemonte', 'Piemonte', 'italian', 'FR,IT', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'pierogis', 'Pierogis', 'polish', 'PL', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'provencal', 'Provencal', 'french', 'FR', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'pueblan', 'Pueblan', 'mexican', 'MX', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'puertorican', 'Puerto Rican', 'caribbean', 'US', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'ramen', 'Ramen', 'japanese', NULL, NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'reunion', 'Reunion', 'french', NULL, 'CH,BR,PL,TR,NZ,DK,AR,AT,CL,JP,AU,MX,DE,NO');
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'rhinelandian', 'Rhinelandian', 'german', 'DE', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'ribatejo', 'Ribatejo', 'portuguese', 'PT', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'robatayaki', 'Robatayaki', 'japanese', 'HK,JP,TW', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'rodizios', 'Rodizios', 'brazilian', 'BR,AR,PT', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'roman', 'Roman', 'italian', 'JP,FR,IT', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'salvadoran', 'Salvadoran', 'latin', 'CA,US', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'sardinian', 'Sardinian', 'italian', 'FR,IT,US', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'senegalese', 'Senegalese', 'african', 'CA,BE,FR,IT,US', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'shanghainese', 'Shanghainese', 'chinese', 'SE,HK,BE,FR,AU,IT,JP,MY,SG,TW,US', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'sicilian', 'Sicilian', 'italian', 'PL,FR,IT,CZ,US', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'soba', 'Soba', 'japanese', 'JP,TW', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'southafrican', 'South African', 'african', 'CA,BE,FR,AU,IT,US', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'sukiyaki', 'Sukiyaki', 'japanese', 'JP,TW', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'szechuan', 'Szechuan', 'chinese', 'GB,NZ,HK,TW,FR,AU,JP,MY,SG,IE,US', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'tacos', 'Tacos', 'mexican', 'MX,US', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'takoyaki', 'Takoyaki', 'japanese', 'JP,TW', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'tamales', 'Tamales', 'mexican', 'MX', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'tempura', 'Tempura', 'japanese', 'JP,TW,SG', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'teochew', 'Teochew', 'chinese', 'HK,MY,TW,SG', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'teppanyaki', 'Teppanyaki', 'japanese', 'HK,TW,JP,AU,MX,SG,NZ,US', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'themedcafes', 'Themed Cafes', 'cafes', 'PH,CH,NO,AR,FI,AT,BE,JP,AU,FR,MY,NZ,US,PL,SE,IE,HK,DK,CA,CL,TW,MX,SG,DE,GB,NL', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'tonkatsu', 'Tonkatsu', 'japanese', 'JP,TW,SG', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'tras_os_montes', 'Tras-os-Montes', 'portuguese', 'PT', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'trinidadian', 'Trinidadian', 'caribbean', 'US', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'turkishravioli', 'Turkish Ravioli', 'turkish', 'TR', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'tuscan', 'Tuscan', 'italian', 'FR,IT,US', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'udon', 'Udon', 'japanese', 'TW,SE,JP,NO,HK,DK,FI', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'unagi', 'Unagi', 'japanese', 'JP,TW', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'venetian', 'Venetian', 'italian', 'FR,IT', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'venezuelan', 'Venezuelan', 'latin', 'CA,ES,CL,FR,AR,PT,US', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'westernjapanese', 'Western Style Japanese Food', 'japanese', 'JP,TW,SG', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'yakiniku', 'Yakiniku', 'japanese', 'JP,TW,SG', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'yakitori', 'Yakitori', 'japanese', 'JP,TW,SG', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'yucatan', 'Yucatan', 'mexican', 'MX', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'gyudon', 'Gyudon', 'donburi', 'JP', NULL);
INSERT INTO categories (id, alias, title, parents, whitelist, blacklist) VALUES (NULL, 'oyakodon', 'Oyakodon', 'donburi', 'JP', NULL);
